name: flutter_complete_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3



dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # State management
  flutter_bloc: ^9.1.0
  # Code generator (mainly used with cubit and retrofit  )
  freezed: ^2.5.0
  # Annotations for the freezed code-generator
  freezed_annotation: ^2.4.1
  # For dependency injection
  get_it: ^8.0.3
  #
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.9.0
  # Annotations for the Json_serializable code generator
  json_annotation: ^4.9.0
  # Networking
  #  powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.8.0+1
  # A Dio client generator
  retrofit: ^4.4.2
  # Code generator for retrofit
  retrofit_generator: ^9.1.0
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0

  # internationalization and localization by the way the second one support us
  intl: ^0.19.0
  easy_localization: ^3.0.6

  # For splash screen
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
